### ISSUE TITLE
¿cómo obtener los enlaces de descargas directamente?

### ISSUE THREAD

**Issue by chrismichaelps** [darkxex/ripexpc#1]
@darkxex  Hola companer@,

¿Quisiera saber cómo logro usted obtener los enlaces de descargas directamente?
El api que yo construí de animeflv, me trae los enlaces, pero primero me redirige a la página de monetización y luego es que me lleva al enlace oficial de descarga,

Este es un ejemplo de la estructura:

```json
// 20200210111148
// https://animeflv.chrismichael.now.sh/api/v1/DownloadLinksByEpsId/28800/tokyo-ghoul-12

{
  "downloads": [
    {
      "server": "MEGA",
      "url": "http://ouo.io/s/y0d65LCP?s=https%3A%2F%2Fmega.nz%2F%23%2155InSaxI%215JTxVNA29LCFNr7c1Fxg0PUBQPVQyXBo4aVF3e06jN0"
    },
    {
      "server": "Zippyshare",
      "url": "http://ouo.io/s/y0d65LCP?s=https%3A%2F%2Fwww61.zippyshare.com%2Fv%2F4KKPr5XK%2Ffile.html"
    },
    {
      "server": "Openload",
      "url": "http://ouo.io/s/y0d65LCP?s=https%3A%2F%2Fopenload.co%2Ff%2FsPXbBXnFikU%2F"
    }
  ]
}
```

**Comment by darkxex** [comment]
Solo hace un url decode. Ejemplo tienes esto http://ouo.io/s/y0d65LCP?s=https%3A%2F%2Fmega.nz%2F%23%2155InSaxI%215JTxVNA29LCFNr7c1Fxg0PUBQPVQyXBo4aVF3e06jN0

Entonces al usar un url decode te queda así http://ouo.io/s/y0d65LCP?s=https://mega.nz/#!55InSaxI!5JTxVNA29LCFNr7c1Fxg0PUBQPVQyXBo4aVF3e06jN0 luego solo cortas lo q necesitas https://mega.nz/#!55InSaxI!5JTxVNA29LCFNr7c1Fxg0PUBQPVQyXBo4aVF3e06jN0

**Comment by chrismichaelps** [comment]
@darkxex 

Pero, como obtienes el .mp4 directamente?

Porque veo que tu programa cuando quiero descargar un episodio detecta directamente el mp4 y te dice hasta cuanta pesa.

**Comment by darkxex** [comment]
Eso ya es más complicado. Pero en si la idea consiste en que tu app se haga pasar por un navegador automatizado y al momento de reproducir el vídeo interceptar el enlace, no es algo q te pueda enseñar pero se llama web scrapping.

**Comment by chrismichaelps** [comment]
Claro, entiendo.
Web scrapping es lo que estoy haciendo.

**Comment by darkxex** [comment]
Claro pero es mucho más avanzado que solo leer el html consiste en monitorear los métodos post y get. Si te fijas la app de este github tiene implementado chronium o sea usa el núcleo de Google Chrome para todo eso. Por eso te digo q es algo q debes estudiar. Los códigos de esta app no son open source.

**Comment by chrismichaelps** [comment]
Entiendo, 
Yo entonces me informare bien de cómo lograrlo.

**Comment by darkxex** [comment]
Dale man, pero te insisto solo monitorea el trafico de un navegador. Puedes usar hasta el Chrome en modo developer para ver cuales son las peticiones que entran y salen.
